//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.WZNTServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WZNTServices.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ParsePixels", ReplyAction="http://tempuri.org/IService/ParsePixelsResponse")]
        double ParsePixels(string File1, string File2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ParsePixels", ReplyAction="http://tempuri.org/IService/ParsePixelsResponse")]
        System.Threading.Tasks.Task<double> ParsePixelsAsync(string File1, string File2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ParseSimilarity", ReplyAction="http://tempuri.org/IService/ParseSimilarityResponse")]
        double ParseSimilarity(string File1, string File2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ParseSimilarity", ReplyAction="http://tempuri.org/IService/ParseSimilarityResponse")]
        System.Threading.Tasks.Task<double> ParseSimilarityAsync(string File1, string File2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Services.WZNTServices.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Services.WZNTServices.IService>, Services.WZNTServices.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double ParsePixels(string File1, string File2) {
            return base.Channel.ParsePixels(File1, File2);
        }
        
        public System.Threading.Tasks.Task<double> ParsePixelsAsync(string File1, string File2) {
            return base.Channel.ParsePixelsAsync(File1, File2);
        }
        
        public double ParseSimilarity(string File1, string File2) {
            return base.Channel.ParseSimilarity(File1, File2);
        }
        
        public System.Threading.Tasks.Task<double> ParseSimilarityAsync(string File1, string File2) {
            return base.Channel.ParseSimilarityAsync(File1, File2);
        }
    }
}
